---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: CICD-Deployment
spec: 
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels: SPC
  strategy: 
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata: 
      name: ECR Image
      labels: SPC-APP
    spec: 
      containers:
        - image: 688567298785.dkr.ecr.ap-south-1.amazonaws.com/development/cicdrepo:latest
          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: Service file- Deployement
spec: 
  selector: SPC-APP
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080